projects:
  Codegen Project:
    schemaPath: ../../serverless/schema.api.graphql
    includes:
      - graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
        region: eu-west-1
        apiId: 7d6jlkbxwfas7ai5oas4rtbsze
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
